WITH DATE_SPINE AS
(
	{{ dbt_utils.date_spine(
		datepart="day",
		start_date="to_date('01/01/1950', 'mm/dd/yyyy')",
		end_date="to_date('12/31/2030','mm/dd/yyy')"
	)
	}}
)
SELECT
CAST(DATE_SPINE.DATE_DAY AS DATE) AS DATE_KEY
,CAST(DATE_PART('doy',DATE_SPINE.DATE_DAY) AS INT) AS DAY_OF_YEAR
,CAST(DATE_PART('dow',DATE_SPINE.DATE_DAY) AS INT) AS DAy_OF_WEEK
,CAST(DATE_PART('week',DATE_SPINE.DATE_DAY) AS INT) AS WEEK_OF_YEAR
,CAST(DATE_PART('month',DATE_SPINE.DATE_DAY) AS INT) AS MONTH
,CAST(DATE_PART('year',DATE_SPINE.DATE_DAY) AS INT) AS YEAR
FROM DATE_SPINE
