version: 2
sources:
  - name: raw 
    database: template1
    tables:
      - name: customer
        description: Raw customer table copied from from the operational database
      - name: order
        description: Raw Order table copied from from the operational database
      - name: address
        description: Raw Address table copied from from the operational database
      - name: product
        description: Raw product table copied from from the operational database
      - name: order_product
        description: Raw OrderProduct table copied from from the operational database
